// ========================================
// MOCK BUILDINGS DATA
// ========================================

const MOCK_BUILDINGS = [
    {
        id: 1,
        name: 'German Administrative Boma',
        code: 'DSH-001',
        era: 'German Colonial',
        year: 1891,
        condition: 'Good',
        status: 'Grade I Listed',
        location: 'City Centre',
        area: '2,840 m²',
        architect: 'Hermann von Wissmann',
        ownership: 'Government of Tanzania',
        style: 'German Colonial Gothic',
        inspected: '2024-03-15',
        rating: '4.0',
        image: 'https://images.unsplash.com/photo-1674334264912-704cb2a24b37?w=600&h=400&fit=crop',
        description: 'The original German administrative headquarters, constructed from coral stone quarried locally. Features characteristic arched colonnades, pitched terracotta roof tiles imported from Hamburg, and a symmetrical façade expressing imperial authority.',
        significance: 'Oldest surviving colonial administrative building in Dar es Salaam and the primary symbol of German colonial presence in East Africa.',
        tags: ['Protected', 'Grade I', '360°'],
        lat: -6.805,
        lng: 39.288
    },
    {
        id: 2,
        name: "St. Joseph's Cathedral",
        code: 'DSH-002',
        era: 'German Colonial',
        year: 1898,
        condition: 'Excellent',
        status: 'Grade I Listed',
        location: 'City Centre',
        area: '1,850 m²',
        architect: 'Father Joseph',
        ownership: 'Catholic Archdiocese',
        style: 'Neo-Gothic',
        inspected: '2024-02-10',
        rating: '4.8',
        image: 'https://images.unsplash.com/photo-1464207687429-7505649dae38?w=600&h=400&fit=crop',
        description: 'Neo-Gothic Catholic cathedral with twin towers, featuring magnificent stained glass windows and a grand nave. The cathedral is a landmark of German colonial architecture.',
        significance: 'One of the oldest and most significant religious buildings in Dar es Salaam, representing the spread of Christianity during the colonial period.',
        tags: ['Protected', 'Grade I', '360°'],
        lat: -6.812,
        lng: 39.291
    },
    {
        id: 3,
        name: 'Azania Front Lutheran Church',
        code: 'DSH-003',
        era: 'German Colonial',
        year: 1898,
        condition: 'Good',
        status: 'Grade II Listed',
        location: 'Kivukoni',
        area: '1,200 m²',
        architect: 'German Missionary Society',
        ownership: 'Lutheran Church of Tanzania',
        style: 'Romanesque Revival',
        inspected: '2024-01-20',
        rating: '4.2',
        image: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&h=400&fit=crop',
        description: 'Historic Lutheran church with distinctive architecture, featuring a prominent clock tower and beautiful waterfront location.',
        significance: 'An important landmark on the Dar es Salaam waterfront, representing the German missionary presence in East Africa.',
        tags: ['Protected', 'Grade II'],
        lat: -6.814,
        lng: 39.292
    },
    {
        id: 4,
        name: "Old Harbour Master's Office",
        code: 'DSH-004',
        era: 'British Colonial',
        year: 1915,
        condition: 'Fair',
        status: 'Grade II Listed',
        location: 'Kivukoni',
        area: '950 m²',
        architect: 'British Admiralty',
        ownership: 'Tanzania Ports Authority',
        style: 'Colonial Maritime',
        inspected: '2024-03-01',
        rating: '3.5',
        image: 'https://images.unsplash.com/photo-1589177900326-900782f88a55?w=600&h=400&fit=crop',
        description: 'Former harbour master office, now part of the port authority. Features distinctive maritime architectural elements and a prime waterfront position.',
        significance: 'Represents the British colonial maritime administration and the development of Dar es Salaam as a major Indian Ocean port.',
        tags: ['Protected', 'Grade II'],
        lat: -6.816,
        lng: 39.285
    },
    {
        id: 5,
        name: 'General Post Office',
        code: 'DSH-005',
        era: 'British Colonial',
        year: 1913,
        condition: 'Poor',
        status: 'Grade II Listed',
        location: 'City Centre',
        area: '1,600 m²',
        architect: 'British Colonial Works Department',
        ownership: 'Government of Tanzania',
        style: 'Edwardian Colonial',
        inspected: '2024-02-28',
        rating: '3.0',
        image: 'https://placehold.co/600x400/eeeeee/666666?text=General+Post+Office',
        description: 'Historic post office building in need of restoration. Features classical colonial architectural elements with a prominent clock tower.',
        significance: 'A key example of British colonial public architecture and an important civic building in central Dar es Salaam.',
        tags: ['Protected', 'Grade II', 'At Risk'],
        lat: -6.810,
        lng: 39.290
    },
    {
        id: 6,
        name: 'Dar es Salaam City Hall',
        code: 'DSH-006',
        era: 'Independence',
        year: 1956,
        condition: 'Good',
        status: 'Grade II Listed',
        location: 'City Centre',
        area: '3,200 m²',
        architect: 'Colonial Office Architects',
        ownership: 'Dar es Salaam City Council',
        style: 'Modern Colonial',
        inspected: '2024-01-05',
        rating: '4.0',
        image: 'https://placehold.co/600x400/eeeeee/666666?text=City+Hall',
        description: 'Historic city hall building with colonial architecture, built just before independence. Features a grand civic façade and large public spaces.',
        significance: 'Represents the transition from colonial to independent governance in Tanzania and remains a symbol of civic administration.',
        tags: ['Protected', 'Grade II'],
        lat: -6.808,
        lng: 39.287
    },
    {
        id: 7,
        name: 'Mnazi Mmoja Hospital Original',
        code: 'DSH-007',
        era: 'British Colonial',
        year: 1920,
        condition: 'At Risk',
        status: 'Proposed',
        location: 'Mnazi Mmoja',
        area: '2,400 m²',
        architect: 'British Colonial Medical Corps',
        ownership: 'Government of Tanzania',
        style: 'Colonial Medical',
        inspected: '2024-03-10',
        rating: '2.5',
        image: 'https://placehold.co/600x400/eeeeee/666666?text=Mnazi+Mmoja+Hospital',
        description: 'Original hospital building currently at risk of demolition. One of the earliest medical facilities in Dar es Salaam.',
        significance: 'Represents the development of healthcare infrastructure in colonial Tanzania and is a rare surviving example of early medical architecture.',
        tags: ['At Risk', 'Proposed', 'Urgent'],
        lat: -6.802,
        lng: 39.280
    },
    {
        id: 8,
        name: 'Dar es Salaam Railway Station',
        code: 'DSH-008',
        era: 'British Colonial',
        year: 1929,
        condition: 'Fair',
        status: 'Grade II Listed',
        location: 'Kariakoo',
        area: '4,500 m²',
        architect: 'British Colonial Railways Department',
        ownership: 'Tanzania Railways Corporation',
        style: 'Colonial Railway',
        inspected: '2024-02-15',
        rating: '3.8',
        image: 'https://placehold.co/600x400/eeeeee/666666?text=Railway+Station',
        description: 'Historic railway station with distinctive colonial architecture. Features a grand concourse, original ceramic tiles, and a Baroque facade.',
        significance: 'A major gateway to Dar es Salaam and a significant example of colonial transport infrastructure in East Africa.',
        tags: ['Protected', 'Grade II', '360°'],
        lat: -6.815,
        lng: 39.279
    },
    {
        id: 9,
        name: 'Askari Monument',
        code: 'DSH-009',
        era: 'British Colonial',
        year: 1927,
        condition: 'Good',
        status: 'Grade I Listed',
        location: 'City Centre',
        area: '50 m²',
        architect: 'James Alexander Stevenson',
        ownership: 'Government of Tanzania',
        style: 'Memorial',
        inspected: '2024-04-10',
        rating: '4.5',
        image: 'https://images.unsplash.com/photo-1549474775-654db4d602cb?w=600&h=400&fit=crop',
        description: 'A bronze statue depicting an Askari soldier, erected to honor the African soldiers who fought in the British Carrier Corps in World War I.',
        significance: 'One of the most famous landmarks in Dar es Salaam, marking the exact center of the city.',
        tags: ['Protected', 'Grade I'],
        lat: -6.8166,
        lng: 39.2882
    },
    {
        id: 10,
        name: 'National Museum of Tanzania',
        code: 'DSH-010',
        era: 'British Colonial',
        year: 1940,
        condition: 'Good',
        status: 'Grade I Listed',
        location: 'Kivukoni',
        area: '4,100 m²',
        architect: 'Unknown',
        ownership: 'Government of Tanzania',
        style: 'Modern',
        inspected: '2024-03-22',
        rating: '4.7',
        image: 'https://images.unsplash.com/photo-1518998053401-878c7355341ce?w=600&h=400&fit=crop',
        description: 'The National Museum consortium holding significant collections on Tanzanian history, culture, and human evolution, including the famous Zinjanthropus skull.',
        significance: 'Crucial repository of Tanzanian heritage and historical artifacts.',
        tags: ['Protected', 'Grade I'],
        lat: -6.8130,
        lng: 39.2941
    },
    {
        id: 11,
        name: 'Ocean Road Hospital',
        code: 'DSH-011',
        era: 'German Colonial',
        year: 1897,
        condition: 'Fair',
        status: 'Grade I Listed',
        location: 'Kivukoni',
        area: '3,500 m²',
        architect: 'German Colonial Administration',
        ownership: 'Ministry of Health',
        style: 'German Colonial',
        inspected: '2024-01-18',
        rating: '4.1',
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&h=400&fit=crop',
        description: 'Historically the first hospital established in Dar es Salaam by the German colonial administration. Now houses the Cancer Institute.',
        significance: 'A landmark in the history of medicine in East Africa and an excellent example of early colonial architecture.',
        tags: ['Protected', 'Grade I'],
        lat: -6.8090,
        lng: 39.2960
    },
    {
        id: 12,
        name: 'State House (Ikulu)',
        code: 'DSH-012',
        era: 'German / British Colonial',
        year: 1922,
        condition: 'Excellent',
        status: 'Grade I Listed',
        location: 'Kivukoni',
        area: '15,000 m²',
        architect: 'British Colonial Works Department',
        ownership: 'Government of Tanzania',
        style: 'African / Colonial Blend',
        inspected: '2024-05-01',
        rating: '4.9',
        image: 'https://images.unsplash.com/photo-1628189874457-3f338d172778?w=600&h=400&fit=crop',
        description: 'The official residence and principal workplace of the President of the United Republic of Tanzania. Originally built by the Germans and later reconstructed by the British.',
        significance: 'The seat of executive power and a highly secure, iconic national heritage building.',
        tags: ['Protected', 'Grade I'],
        lat: -6.8095,
        lng: 39.2925
    }
];

console.log('MOCK_BUILDINGS loaded:', MOCK_BUILDINGS.length, 'buildings');